//THIS FILE IS AUTOGENERATED BY GHOSTCOMPILER. DON'T MODIFY OR ALTER.
using AOT;
using Unity.Burst;
using Unity.Networking.Transport;
using Unity.Entities;
using Unity.Collections;
using Unity.NetCode;
using Unity.Transforms;
using Unity.Mathematics;


namespace Asteroids.Mixed.Generated
{
    [BurstCompile]
    public struct LevelLoadRequestSerializer : IComponentData, IRpcCommandSerializer<LevelLoadRequest>
    {
        public void Serialize(ref DataStreamWriter writer, in LevelLoadRequest data)
        {
            writer.WriteInt((int) data.width);
            writer.WriteInt((int) data.height);
            writer.WriteFloat(data.playerForce);
            writer.WriteFloat(data.bulletVelocity);
        }

        public void Deserialize(ref DataStreamReader reader, ref LevelLoadRequest data)
        {
            data.width = (int) reader.ReadInt();
            data.height = (int) reader.ReadInt();
            data.playerForce = reader.ReadFloat();
            data.bulletVelocity = reader.ReadFloat();
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(RpcExecutor.ExecuteDelegate))]
        private static void InvokeExecute(ref RpcExecutor.Parameters parameters)
        {
            RpcExecutor.ExecuteCreateRequestComponent<LevelLoadRequestSerializer, LevelLoadRequest>(ref parameters);
        }

        static PortableFunctionPointer<RpcExecutor.ExecuteDelegate> InvokeExecuteFunctionPointer =
            new PortableFunctionPointer<RpcExecutor.ExecuteDelegate>(InvokeExecute);
        public PortableFunctionPointer<RpcExecutor.ExecuteDelegate> CompileExecute()
        {
            return InvokeExecuteFunctionPointer;
        }
    }
    class LevelLoadRequestRpcCommandRequestSystem : RpcCommandRequestSystem<LevelLoadRequestSerializer, LevelLoadRequest>
    {
        [BurstCompile]
        protected struct SendRpc : IJobEntityBatch
        {
            public SendRpcData data;
            public void Execute(ArchetypeChunk chunk, int orderIndex)
            {
                data.Execute(chunk, orderIndex);
            }
        }
        protected override void OnUpdate()
        {
            var sendJob = new SendRpc{data = InitJobData()};
            ScheduleJobData(sendJob);
        }
    }
}
